use_frameworks!
target "worshipsongs" do
 pod 'FMDB'
 pod 'YouTubePlayer', :git => 'https://github.com/gilesvangruisen/Swift-YouTube-Player.git', :tag => 'v0.4.0', :submodules => true
 pod "KCFloatingActionButton", :git => 'https://github.com/kciter/KCFloatingActionButton.git', :tag => '2.1.2', :submodules => true
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
