use_frameworks!
target "worshipsongs" do
 pod 'FMDB'
 pod 'YouTubePlayer', :git => 'https://github.com/gilesvangruisen/Swift-YouTube-Player.git', :tag => 'v0.4.0', :submodules => true
 pod "KCFloatingActionButton", :git => 'https://github.com/kciter/KCFloatingActionButton.git', :tag => '2.1.2', :submodules => true
 pod 'FileBrowser', :git => 'https://github.com/marmelroy/FileBrowser.git', :tag => '0.2.0', :submodules => true
 pod 'SimplePDFSwift', :git => 'https://github.com/ishaq/SimplePDF.git', :tag => '0.2.1', :submodules => true
end

target 'worshipsongsTests' do
  pod 'FMDB'
  pod 'YouTubePlayer', :git => 'https://github.com/gilesvangruisen/Swift-YouTube-Player.git', :tag => 'v0.4.0', :submodules => true
  pod "KCFloatingActionButton", :git => 'https://github.com/kciter/KCFloatingActionButton.git', :tag => '2.1.2', :submodules => true
  pod 'FileBrowser', :git => 'https://github.com/marmelroy/FileBrowser.git', :tag => '0.2.0', :submodules => true
  pod 'SimplePDFSwift', :git => 'https://github.com/ishaq/SimplePDF.git', :tag => '0.2.1', :submodules => true
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
